[env:vintlabs-devkit-v1]
platform = espressif32
board = vintlabs-devkit-v1
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions_8M.csv
framework = arduino
monitor_speed = 115200

build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_ESP32_RELEASE_3_0
    ; THIS IS THE FIX: It tells the Firebase library to use the Core 3.x LittleFS
    -D MB_FS_LITTLEFS_ESP32
    -D USER_CONFIG_LITTLEFS_FS

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3
    mobizt/Firebase ESP32 Client @ ^4.4.17
    ; CRITICAL: DO NOT list LITTLEFS or lorol here. 
    ; It is already built into your board's framework.