#!/usr/bin/env python3

import hashlib
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[1]

# Enrollment script writes here
DEVICES_FILE = PROJECT_DIR / "scripts" / "devices.json"

GENERATED_DIR = PROJECT_DIR / "generated"
GENERATED_HEADER = GENERATED_DIR / "device_config.generated.h"

# Device-specific AI Engine profiles:
# device_ai_engines/<deviceId>/AI_Engine.h
AI_ENGINE_PROFILES_DIR = PROJECT_DIR / "device_ai_engines"
AI_ENGINE_FILENAME = "AI_Engine.h"

PIO_EXE = r"C:\Users\mdroo\.platformio\penv\Scripts\platformio.exe"
DEFAULT_PIO_ENV = "vintlabs-devkit-v1"

REQUIRED_FIELDS = [
    "customer",
    "label",
    "deviceId",
    "firmwareVersion",
    "chipId",
    "macAddress",
    "board",
    "otaJsonName",
    "otaBinName",
    "firebasePublic",
]


def fail(msg):
    print(f"\nERROR: {msg}")
    sys.exit(1)


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_devices():
    if not DEVICES_FILE.exists():
        fail(f"devices.json not found:\n{DEVICES_FILE}")

    try:
        return json.loads(DEVICES_FILE.read_text(encoding="utf-8"))
    except Exception as e:
        fail(f"Could not read devices.json: {e}")


def save_devices(devices):
    try:
        DEVICES_FILE.write_text(json.dumps(devices, indent=4) + "\n", encoding="utf-8")
    except Exception as e:
        fail(f"Could not write devices.json: {e}")


def increment_firmware_version(version):
    """
    Increment the last numeric component while preserving the prefix/separators.

    Examples:
      T-1.0.0    -> T-1.0.1
      P_1.1.5    -> P_1.1.6
      10.7.0     -> 10.7.1
      T-1.0.0.9  -> T-1.0.0.10
    """
    v = str(version).strip()
    m = re.search(r"(\d+)(?!.*\d)", v)
    if not m:
        fail(f"Cannot auto-increment firmwareVersion because it has no number: {version}")

    start, end = m.span(1)
    n = int(m.group(1)) + 1
    return v[:start] + str(n) + v[end:]


def validate_device(d):
    missing = [k for k in REQUIRED_FIELDS if k not in d or str(d[k]).strip() == ""]
    if missing:
        fail("Device entry is missing required fields: " + ", ".join(missing))

    if d["deviceId"] not in d["otaBinName"]:
        fail(f'otaBinName should contain deviceId. Got: {d["otaBinName"]}')

    if d["deviceId"] not in d["otaJsonName"]:
        fail(f'otaJsonName should contain deviceId. Got: {d["otaJsonName"]}')


def write_generated_header(d):
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    header = f'''#pragma once

#include <Arduino.h>

// AUTO-GENERATED by scripts/build_device.py
// Do not edit this file manually.

const String BUILD_DEVICE_ID = "{d["deviceId"]}";
const String BUILD_DEVICE_LABEL = "{d["label"]}";
const String BUILD_FW_VERSION = "{d["firmwareVersion"]}";

const String BUILD_EXPECTED_MAC = "{d["macAddress"]}";
const String BUILD_EXPECTED_CHIP = "{d["chipId"]}";
const String BUILD_EXPECTED_BOARD = "{d["board"]}";
'''

    GENERATED_HEADER.write_text(header, encoding="utf-8")
    return GENERATED_HEADER



def find_active_ai_engine_header():
    lib_dir = PROJECT_DIR / "lib"

    if not lib_dir.exists():
        fail(f"PlatformIO lib directory not found:\n{lib_dir}")

    candidates = sorted(
        path for path in lib_dir.rglob(AI_ENGINE_FILENAME)
        if path.is_file()
    )

    if not candidates:
        fail(f"No active AI_Engine.h found under:\n{lib_dir}")

    if len(candidates) > 1:
        files = "\n".join(f"  - {path}" for path in candidates)
        fail(
            "More than one AI_Engine.h was found under lib. "
            "The builder cannot safely choose one:\n" + files
        )

    return candidates[0]


def select_device_ai_engine(d):
    device_id = str(d["deviceId"]).strip()
    source = AI_ENGINE_PROFILES_DIR / device_id / AI_ENGINE_FILENAME
    destination = find_active_ai_engine_header()

    if not source.exists():
        fail(
            f"Device-specific AI_Engine.h is missing for {device_id}:\n"
            f"{source}"
        )

    copy_and_verify(source, destination)

    source_hash = sha256_file(source)
    destination_hash = sha256_file(destination)

    if source_hash != destination_hash:
        fail(
            "AI_Engine.h verification failed after copy.\n"
            f"Source: {source}\nDestination: {destination}"
        )

    print("\nAI Engine selected:")
    print(f"  device      : {device_id}")
    print(f"  source      : {source}")
    print(f"  active file : {destination}")
    print(f"  sha256      : {source_hash}")

    return {
        "source": source,
        "destination": destination,
        "sha256": source_hash,
    }


def run_platformio(pio_env):
    print("\nRunning PlatformIO build...")
    result = subprocess.run(
        [PIO_EXE, "run", "-e", pio_env],
        cwd=PROJECT_DIR,
    )

    if result.returncode != 0:
        fail("PlatformIO build failed.")


def ask_yes_no(prompt, default=False):
    suffix = " [Y/n]: " if default else " [y/N]: "

    while True:
        answer = input(prompt + suffix).strip().lower()

        if answer == "":
            return default

        if answer in ("y", "yes"):
            return True

        if answer in ("n", "no"):
            return False

        print("Please answer y or n.")


def make_ota_json(d, dist_bin, ota_bin_name=None, ota_json_name=None):
    device_id = d["deviceId"]
    bin_name = ota_bin_name or d["otaBinName"]
    json_name = ota_json_name or d["otaJsonName"]

    firmware_path = f"/devices/{device_id}/{bin_name}"
    firmware_url = f"https://aiesdoser.web.app{firmware_path}"

    return {
        "ok": True,
        "deviceId": device_id,
        "customer": d["customer"],
        "label": d["label"],
        "firmwareVersion": d["firmwareVersion"],
        "version": d["firmwareVersion"],
        "board": d["board"],
        "chipId": d["chipId"],
        "macAddress": d["macAddress"],
        "otaBinName": bin_name,
        "otaJsonName": json_name,
        "firmwarePath": firmware_path,
        "firmwareUrl": firmware_url,
        "binUrl": firmware_url,
        "size": dist_bin.stat().st_size,
        "sha256": sha256_file(dist_bin),
        "builtAt": datetime.now().isoformat(timespec="seconds"),
        "aiEngineProfile": d.get("_aiEngineProfile", d["deviceId"]),
        "aiEngineSha256": d.get("_aiEngineSha256", ""),
    }


def copy_and_verify(src, dst):
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)

    if not dst.exists():
        fail(f"Copy failed, file missing:\n{dst}")

    if src.stat().st_size != dst.stat().st_size:
        fail(f"Copy failed, size mismatch:\nSRC: {src}\nDST: {dst}")


def main():
    print("========================================")
    print("      AIES DEVICE BUILDER v3")
    print("========================================")

    devices = load_devices()

    print("\nAvailable devices:")
    for name in devices:
        print(f"  - {name}")

    device_name = input("\nDevice to build: ").strip()

    if device_name not in devices:
        fail(f"Unknown device: {device_name}")

    d = devices[device_name]
    validate_device(d)

    old_fw_version = str(d["firmwareVersion"]).strip()
    bump_version = ask_yes_no(
        f'Increment firmware version for this build? {old_fw_version} -> {increment_firmware_version(old_fw_version)}',
        default=True,
    )

    if bump_version:
        new_fw_version = increment_firmware_version(old_fw_version)
        d["firmwareVersion"] = new_fw_version
        devices[device_name] = d
        save_devices(devices)
        print(f"\nFirmware version incremented:")
        print(f"  {old_fw_version} -> {new_fw_version}")
        print(f"  saved to: {DEVICES_FILE}")
    else:
        print(f"\nFirmware version unchanged: {old_fw_version}")

    validate_device(d)

    first_time_build = ask_yes_no(
        "Is this a FIRST-TIME build for this device/customer? "
        "If yes, I will also create firmware.bin and firmware.json",
        default=False,
    )

    pio_env = d.get("board", DEFAULT_PIO_ENV) or DEFAULT_PIO_ENV

    header_path = write_generated_header(d)

    print("\nGenerated:")
    print(header_path)

    print("\nDevice:")
    print(f'  deviceId : {d["deviceId"]}')
    print(f'  customer : {d["customer"]}')
    print(f'  label    : {d["label"]}')
    print(f'  version  : {d["firmwareVersion"]}')
    print(f'  mac      : {d["macAddress"]}')
    print(f'  chip     : {d["chipId"]}')
    print(f'  board    : {d["board"]}')

    ai_engine = select_device_ai_engine(d)
    d["_aiEngineProfile"] = d["deviceId"]
    d["_aiEngineSha256"] = ai_engine["sha256"]

    run_platformio(pio_env)

    print("\nBUILD SUCCESS")

    build_bin = PROJECT_DIR / ".pio" / "build" / pio_env / "firmware.bin"

    if not build_bin.exists():
        fail(f"firmware.bin not found:\n{build_bin}")

    device_id = d["deviceId"]

    # Local release folder:
    # dist/reefDoser3/reefDoser3.bin
    # dist/reefDoser3/reefDoser3.json
    dist_dir = PROJECT_DIR / "dist" / device_id
    dist_bin = dist_dir / d["otaBinName"]
    dist_json = dist_dir / d["otaJsonName"]
    first_time_dist_bin = dist_dir / "firmware.bin"
    first_time_dist_json = dist_dir / "firmware.json"

    dist_dir.mkdir(parents=True, exist_ok=True)
    copy_and_verify(build_bin, dist_bin)

    dist_ai_engine = dist_dir / "AI_Engine.h"
    copy_and_verify(ai_engine["destination"], dist_ai_engine)

    ota = make_ota_json(d, dist_bin)
    dist_json.write_text(json.dumps(ota, indent=4), encoding="utf-8")

    if not dist_json.exists():
        fail(f"OTA JSON was not created:\n{dist_json}")

    first_time_ota = None
    if first_time_build:
        copy_and_verify(build_bin, first_time_dist_bin)
        first_time_ota = make_ota_json(
            d,
            first_time_dist_bin,
            ota_bin_name="firmware.bin",
            ota_json_name="firmware.json",
        )
        first_time_dist_json.write_text(json.dumps(first_time_ota, indent=4), encoding="utf-8")

        if not first_time_dist_json.exists():
            fail(f"First-time OTA JSON was not created:\n{first_time_dist_json}")

    # Firebase public device folder:
    # C:/Users/mdroo/OneDrive/Firebase/aiesdoser/public/devices/reefDoser3/reefDoser3.bin
    # C:/Users/mdroo/OneDrive/Firebase/aiesdoser/public/devices/reefDoser3/reefDoser3.json
    firebase_public = Path(d["firebasePublic"])
    firebase_device_dir = firebase_public / "devices" / device_id
    firebase_bin = firebase_device_dir / d["otaBinName"]
    firebase_json = firebase_device_dir / d["otaJsonName"]
    first_time_firebase_bin = firebase_device_dir / "firmware.bin"
    first_time_firebase_json = firebase_device_dir / "firmware.json"

    copy_and_verify(dist_bin, firebase_bin)
    copy_and_verify(dist_json, firebase_json)

    if first_time_build:
        copy_and_verify(first_time_dist_bin, first_time_firebase_bin)
        copy_and_verify(first_time_dist_json, first_time_firebase_json)

    print("\nFirmware copied to:")
    print(f"  {dist_bin}")

    print("\nOTA JSON created:")
    print(f"  {dist_json}")

    print("\nFirebase files copied to:")
    print(f"  {firebase_bin}")
    print(f"  {firebase_json}")

    if first_time_build:
        print("\nFirst-time firmware files also created:")
        print(f"  {first_time_dist_bin}")
        print(f"  {first_time_dist_json}")
        print(f"  {first_time_firebase_bin}")
        print(f"  {first_time_firebase_json}")

    print("\nOTA URL paths:")
    print(f'  JSON: /devices/{device_id}/{d["otaJsonName"]}')
    print(f'  BIN : /devices/{device_id}/{d["otaBinName"]}')

    if first_time_build:
        print("\nFirst-time OTA URL paths:")
        print(f"  JSON: /devices/{device_id}/firmware.json")
        print(f"  BIN : /devices/{device_id}/firmware.bin")

    print("\nVerification:")
    print(f'  size   : {ota["size"]}')
    print(f'  sha256 : {ota["sha256"]}')

    if first_time_ota:
        print("\nFirst-time verification:")
        print(f'  size   : {first_time_ota["size"]}')
        print(f'  sha256 : {first_time_ota["sha256"]}')

    print("\n========================================")
    print("BUILD COMPLETE - READY FOR FIREBASE DEPLOY")
    print("========================================")


if __name__ == "__main__":
    main()
